export const mapMarkers = [
    {
        id: '9',
        type: 'buildings',
        name: 'Arts and Design Workshop Bldg. 2',
        icon: 'building',
        coordinates: [123.898096, 10.323937],
    },
    {
        id: '10',
        type: 'buildings',
        name: 'Arts and Science Extension Bldg. (ASX)',
        icon: 'building',
        coordinates: [123.897949, 10.323871],
    },
    {
        id: '8',
        type: 'buildings',
        name: 'Arts and Design Workshop Bldg.',
        icon: 'building',
        coordinates: [123.898273, 10.323521],
    },
    {
        id: '7',
        type: 'buildings',
        name: 'Undergraduate Building',
        icon: 'building',
        coordinates: [123.897928, 10.323404],
    },
    {
        id: '6b',
        type: 'buildings',
        name: 'Management Bldg. 1',
        icon: 'building',
        coordinates: [123.897771, 10.32311],
    },
    {
        id: '6a',
        type: 'buildings',
        name: 'Management Administration',
        icon: 'building',
        coordinates: [123.897737, 10.32278],
    },
    {
        id: '6c',
        type: 'buildings',
        name: 'Management Bldg. 2',
        icon: 'building',
        coordinates: [123.897714, 10.322545],
    },
    {
        id: '6',
        type: 'buildings',
        name: 'School of Management',
        icon: 'building',
        coordinates: [123.8978, 10.322611],
    },
    {
        id: '1',
        type: 'buildings',
        name: 'Administration Building',
        icon: 'building',
        coordinates: [123.898199, 10.322329],
    },
    {
        id: '2',
        type: 'buildings',
        icon: 'building',
        name: 'Science Building',
        coordinates: [123.897939, 10.322249],
    },
    {
        id: '5d',
        type: 'buildings',
        name: 'Lihangin Hall',
        icon: 'building',
        coordinates: [123.897523, 10.322135],
    },
    {
        id: '5a',
        type: 'buildings',
        name: 'Balay Varangao',
        icon: 'building',
        coordinates: [123.897562, 10.321921],
    },
    {
        id: '5',
        type: 'buildings',
        name: 'Residence Halls',
        icon: 'building',
        coordinates: [123.89759, 10.321825],
    },
    {
        id: '5b',
        type: 'buildings',
        name: 'Lalahon Hall',
        icon: 'building',
        coordinates: [123.897685, 10.321631],
    },
    {
        id: '5c',
        type: 'buildings',
        name: 'Liadlaw Hall',
        icon: 'building',
        coordinates: [123.897555, 10.321638],
    },
    {
        id: 'A9',
        type: 'activity',
        name: 'Amphitheater/Sunset Garden',
        icon: 'star',
        coordinates: [123.897727, 10.323369],
    },
    {
        id: 'A8',
        type: 'activity',
        name: 'Volleyball Court',
        icon: 'volleyball',
        coordinates: [123.898368, 10.323105],
    },
    {
        id: 'A7',
        type: 'activity',
        name: 'Basketball Court',
        icon: 'basketball',
        coordinates: [123.89792, 10.322698],
    },
    {
        id: 'A6',
        type: 'activity',
        name: 'Undergraduate Cottages',
        icon: 'tent',
        coordinates: [123.898161, 10.322744],
    },
    {
        id: 'P1',
        type: 'security',
        name: 'COS Bldg. Parking',
        icon: 'car',
        coordinates: [123.898083, 10.322275],
    },
    {
        id: 'P2',
        type: 'security',
        name: 'Canteen Parking',
        icon: 'car',
        coordinates: [123.897778, 10.321974],
    },
    {
        id: 'P3',
        type: 'security',
        name: 'Library Parking',
        icon: 'car',
        coordinates: [123.898128, 10.321456],
    },
    {
        id: 'P4',
        type: 'security',
        name: 'Motorcycle Parking',
        icon: 'bike',
        coordinates: [123.898424, 10.322876],
    },
    {
        id: 'P5',
        type: 'security',
        name: 'Undergraduate Bldg. Parking',
        icon: 'car',
        coordinates: [123.897979, 10.32356],
    },
    {
        id: 'P6',
        type: 'security',
        name: 'AS Motorcycle Parking',
        icon: 'bike',
        coordinates: [123.898972, 10.322907],
    },
    {
        id: 'P7',
        type: 'security',
        name: 'AS Parking',
        icon: 'car',
        coordinates: [123.898907, 10.323085],
    },
    {
        id: 'A4',
        type: 'activity',
        name: 'Admin Field',
        icon: 'target',
        coordinates: [123.898449, 10.321591],
    },
    {
        id: 'G1',
        type: 'security',
        name: 'Entrance Gate Guard House',
        icon: 'shield',
        coordinates: [123.898713, 10.321827],
    },
    {
        id: 'G3',
        type: 'security',
        name: 'High School Guard House',
        icon: 'shield',
        coordinates: [123.898842, 10.322043],
    },
    {
        id: 'G4',
        type: 'security',
        name: 'AS Guard House',
        icon: 'shield',
        coordinates: [123.898689, 10.322791],
    },
    {
        id: 'G2',
        type: 'security',
        name: 'Exit Gate Guard House',
        icon: 'shield',
        coordinates: [123.898521, 10.322888],
    },
    {
        id: 'A2',
        type: 'activity',
        name: 'Admin Cottages',
        icon: 'tent',
        coordinates: [123.89824, 10.321963],
    },
    {
        id: 'A3',
        type: 'activity',
        name: 'Malacañang Cottage',
        icon: 'tent',
        coordinates: [123.898494, 10.321822],
    },
    {
        id: 'A1',
        type: 'activity',
        name: 'Oblation Square',
        icon: 'star',
        coordinates: [123.898569, 10.322395],
    },
    {
        id: 'A5',
        type: 'activity',
        name: 'College Mini Stage',
        icon: 'star',
        coordinates: [123.898634, 10.321482],
    },
    {
        id: 'A10',
        type: 'activity',
        name: 'High School Open Field',
        icon: 'star',
        coordinates: [123.899085, 10.32205],
    },
    {
        id: 'A11',
        type: 'activity',
        name: 'High School Open Court',
        icon: 'star',
        coordinates: [123.899468, 10.321972],
    },
    {
        id: 'A12',
        type: 'activity',
        name: 'High School Covered Court',
        icon: 'star',
        coordinates: [123.899965, 10.321848],
    },
    {
        id: 'A13',
        type: 'activity',
        name: 'Soccer Field',
        icon: 'football',
        coordinates: [123.89982, 10.322717],
    },
    {
        id: '4',
        type: 'buildings',
        name: 'Library Building',
        icon: 'book',
        coordinates: [123.897985, 10.321434],
    },
    {
        id: '3',
        type: 'buildings',
        name: 'Technology Innovation Center Bldg.',
        icon: 'building',
        coordinates: [123.897882, 10.321726],
    },
    {
        id: '3b',
        type: 'buildings',
        name: 'Clinic',
        icon: 'clinic',
        coordinates: [123.897962, 10.321684],
    },
    {
        id: '3a',
        type: 'buildings',
        name: 'Cafeteria',
        icon: 'food',
        coordinates: [123.897946, 10.321814],
    },
    {
        id: '13',
        type: 'buildings',
        name: 'Cebu Cultural Center',
        icon: 'building',
        coordinates: [123.899158, 10.322484],
    },
    {
        id: '11',
        type: 'buildings',
        name: 'Arts and Sciences (AS) Bldg.',
        icon: 'building',
        coordinates: [123.899292, 10.323221],
    },
    {
        id: '11a',
        type: 'buildings',
        name: 'AS Conference Hall',
        icon: 'building',
        coordinates: [123.899462, 10.323281],
    },
    {
        id: '11b',
        type: 'buildings',
        name: 'AS East Wing',
        icon: 'building',
        coordinates: [123.89943, 10.323088],
    },
    {
        id: '11c',
        type: 'buildings',
        name: 'AS West Wing',
        icon: 'building',
        coordinates: [123.899506, 10.323501],
    },
    {
        id: '14',
        type: 'buildings',
        name: 'High School Area',
        icon: 'building',
        coordinates: [123.899711, 10.321967],
    },
    {
        id: '12',
        type: 'buildings',
        name: 'Union Building',
        icon: 'building',
        coordinates: [123.899779, 10.323402],
    },
];

export const mockBuildingsData = {
    '12': {
        id: '12',
        name: 'Union Building',
        image: '/assets/images/buildings/union.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: "Engineering Dean's Office" },
                    { name: 'Department of Civil Engineering' },
                    { name: 'Engineering Student Council Office' },
                    { name: 'Engineering Library' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Department of Mechanical Engineering' },
                    { name: 'Mechanical Engineering Laboratories' },
                    { name: 'Faculty Lounge' },
                    { name: 'Conference Room' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '3rd Floor',
                facilities: [
                    { name: 'Department of Electrical Engineering' },
                    { name: 'Electrical Engineering Laboratories' },
                    { name: 'Computer Laboratory' },
                    { name: 'Research Center' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '4th Floor',
                facilities: [
                    { name: 'Department of Chemical Engineering' },
                    { name: 'Chemical Engineering Laboratories' },
                    { name: 'Innovation Center' },
                    { name: 'Student Study Area' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
        departments: [
            'Civil Engineering',
            'Mechanical Engineering',
            'Electrical Engineering',
            'Chemical Engineering',
        ],
        contactNumber: '123-456-7890',
        email: 'engineering@university.edu',
        dean: 'Dr. Robert Johnson',
    },
    '9': {
        id: '9',
        name: 'Fine Arts Workshop Bldg. 2',
        image: '/assets/images/buildings/workshop2.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [{ name: 'Workshop 3' }],
            },
        ],
    },
    '10': {
        id: '10',
        name: 'Arts and Science Extension Bldg. (ASX)',
        image: '/assets/images/buildings/asx.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Electrical room' },
                    { name: 'ASX 101' },
                    { name: 'ASX 102' },
                    { name: 'ASX 103' },
                    { name: 'ASX 104' },
                    { name: 'Male Restroom' },
                    { name: 'Female Restroom' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Faculty Lounge' },
                    { name: 'ASX 205' },
                    { name: 'ASX 208' },
                    { name: 'ASX 206' },
                    { name: 'ASX 207' },
                ],
            },
        ],
    },

    '8': {
        id: '8',
        name: 'Fine Arts Workshop Bldg.',
        image: '/assets/images/buildings/workshop1.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [{ name: 'Workshop 1' }],
            },
            {
                name: '2nd Floor',
                facilities: [{ name: 'Workshop 2' }],
            },
            {
                name: '3rd Floor',
                facilities: [
                    { name: 'Filipiniana Section' },
                    { name: 'Archives' },
                    { name: 'Special Collections' },
                    { name: 'Multimedia Room' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },

    '7': {
        id: '7',
        name: 'Undergraduate Building',
        image: '/assets/images/buildings/undergraduate.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    {
                        name: 'Teaching and Learning Resources Center',
                        email: 'lrc.upcebu@up.edu.ph',
                        contactNumber: '(032) 232 8187',
                    },
                    { name: 'Lawak Sinehan' },
                    { name: 'Department of Biology and Environmental Science' },
                    { name: 'UG123A Zoology Lab' },
                    { name: 'UG123B Zoology Lab' },
                    { name: 'UG122A Lecture Room' },
                    { name: 'UG122B Physics Laboratory' },
                    { name: 'UG124 Chemistry Stock Room' },
                    { name: 'UG125A Chemistry Lab' },
                    { name: 'UG125B Chemistry Lab' },
                    { name: 'UG126A' },
                    { name: 'UG126B General Biology Lab' },
                    { name: 'UG126C Botany Lab' },
                    { name: 'UG127' },
                    { name: 'UG126D MSES Room' },
                    { name: 'UG114 Computer Laboratory' },
                    { name: 'UG115A Bioassay Lab' },
                    { name: 'UG115B DBES Lecture room' },
                    { name: 'UG116A Natural Products Lab' },
                    { name: 'UG116B' },
                    { name: 'UG117 Molecular Diagnostic Lab' },
                    { name: 'UG118 Computer Laboratory' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'JOYA Gallery' },
                    { name: 'College of Communication Arts and Design Office' },
                    { name: 'JOYA Gallery Office' },
                    { name: 'MMF' },
                    { name: 'News Room' },
                    { name: 'MMR' },
                    { name: 'TV Lab' },
                    { name: 'CME' },
                    { name: 'UG228' },
                    { name: 'FABLAB' },
                    { name: 'UG220 Painting Room' },
                    { name: 'UG219' },
                    { name: 'UG217' },
                    { name: 'UG215' },
                    { name: 'UG218' },
                    { name: 'UG216' },
                    { name: 'UG214' },
                ],
            },
            {
                name: '3rd Floor',
                facilities: [
                    { name: 'Department of History' },
                    { name: 'Department of Anthropology' },
                    { name: 'Faculty Rooms' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },

    '6b': {
        id: '6b',
        name: 'Management Bldg. 1',
        image: '/assets/images/buildings/man1.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: '101A' },
                    { name: '101B' },
                    { name: '102A' },
                    { name: '102B' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [{ name: '202' }, { name: 'Case Room' }],
            },
            {
                name: '3rd Floor',
                facilities: [{ name: 'Roofdeck' }],
            },
        ],
    },
    '6a': {
        id: '6a',
        name: 'Management Administration',
        image: '/assets/images/buildings/manAdmin.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Office of the Dean' },
                    { name: 'Office of the College Secretary' },
                ],
            },
        ],
    },
    '6c': {
        id: '6c',
        name: 'Management Bldg. 2',
        image: '/assets/images/buildings/man2.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'RM103' },
                    { name: 'RM104' },
                    { name: 'Stock room' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [{ name: 'RM203' }, { name: 'RM204' }],
            },
        ],
    },

    '6': {
        id: '6',
        name: 'School of Management',
        image: '/assets/images/buildings/man.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'CAS Administration Office' },
                    { name: 'Student Lounge' },
                    { name: 'Conference Room' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Faculty Offices' },
                    { name: 'Research Centers' },
                    { name: 'Meeting Rooms' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },
    '1': {
        id: '1',
        name: 'Administration Building',
        image: '/assets/images/buildings/admin.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: 'First Floor',
                facilities: [
                    { name: 'PE Office' },
                    { name: 'Office of the Chancellor' },
                    {
                        name: 'Office of the Vice Chancellor for Academic Affairs',
                        email: 'ovcaa.upcebu@up.edu.ph',
                    },
                    {
                        name: 'Office of the Vice Chancellor for Administration',
                        email: 'ovca.upcebu@up.edu.ph',
                    },
                    { name: 'Mindscape' },
                    { name: 'Myths' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Art Exhibit' },
                    { name: 'Office of Student Affairs' },
                    { name: 'ILC-AVR' },
                    { name: 'Office of the Campus Architect' },
                    { name: 'Office for the Initiatives in Culture and Arts' },
                    { name: 'Boardroom' },
                ],
            },
        ],
    },

    '2': {
        id: '2',
        name: 'College of Science Building',
        image: '/assets/images/buildings/cos.jpg',
        slug: 'science-building',
        type: 'building',
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    {
                        name: 'Budget Office',
                        contactNumber: 'Local - 122/305',
                        email: 'budget.upcebu@up.edu.ph',
                    },
                    {
                        name: 'Office of the University Registrar',
                        contactNumber: 'Local - 324',
                        email: 'our.upcebu@up.edu.ph',
                    },
                    {
                        name: 'Supply and Property Management Office',
                        email: 'spmo.upcebu@up.edu.ph',
                        contactNumber: 'Local - 325 | Direct - (032) 233 3497',
                    },
                    {
                        name: 'College of Science',
                        contactNumber: 'Local - 311',
                        email: 'cos.upcebu@up.edu.ph',
                    },
                    {
                        name: 'Bids and Awards Committee Office',
                        contactNumber: 'Local - 317',
                        email: 'bac_sec.upcebu@up.edu.ph',
                    },
                    {
                        name: 'Cash Office',
                        contactNumber: 'Local - 101',
                        email: 'cash.upcebu@up.edu.ph',
                    },
                    {
                        name: 'Accounting Office',
                        contactNumber: 'Local - 104',
                        email: 'accounting.upcebu@up.edu.ph',
                    },
                    { name: 'Server Room' },
                    { name: 'Emergency Exit 1' },
                    { name: 'Emergency Exit 2' },
                    { name: 'Emergency Exit 3' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
            {
                name: 'Mezzanine Floor',
                facilities: [
                    { name: 'Stock Room' },
                    {
                        name: 'Human Resource Office',
                        contactNumber: 'Local - 319',
                        email: 'hrdo.upcebu@up.edu.ph',
                    },
                    {
                        name: 'Legal Office',
                        contactNumber: 'Local - 326',
                        email: 'legal.upcebu@up.edu.ph',
                    },
                    { name: 'Spare Room' },
                    { name: 'Resident Psychologist' },
                    { name: 'Common Conference Room & Staff Lounge' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: '201 Lecture Room' },
                    { name: '202 Lecture Room' },
                    { name: '203 Lecture Room' },
                    {
                        name: '204 Mathematics and Statistics Office',
                        contactNumber: 'Local - 205',
                        email: 'math.upcebu@up.edu.ph',
                    },
                    { name: 'Emergency Exit 1' },
                    { name: 'Emergency Exit 2' },
                    { name: 'Emergency Exit 3' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
            {
                name: '3rd Floor',
                facilities: [
                    { name: '301' },
                    { name: '302 Robotics and Internet of Things Group' },
                    { name: '303 Bioinformatics Research Interest Group' },
                    { name: '304' },
                    { name: '305' },
                    { name: '306' },
                    { name: '307 Image and Video Analysis Research Group' },
                    { name: '308 Optimization Research Group' },
                    { name: '310 Natural Language Processing Group' },
                    { name: '311 Mini Library' },
                    { name: '312 Office of the Chairperson' },
                    {
                        name: '204 Department of Computer Science Office',
                        contactNumber: 'Local - 206',
                        email: 'dcs.upcebu@up.edu.ph',
                    },
                    { name: 'Emergency Exit 1' },
                    { name: 'Emergency Exit 2' },
                    { name: 'Emergency Exit 3' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
            {
                name: '4th Floor',
                facilities: [
                    { name: '401 Computer Laboratory' },
                    { name: '402 Computer Laboratory' },
                    { name: '403 Computer Laboratory' },
                    { name: '404 Computer Laboratory' },
                    { name: '405 Lecture Room' },
                    { name: '406 Lecture Room' },
                    { name: '407 Lecture Room' },
                    { name: '408 Lecture Room' },
                    { name: 'Emergency Exit 1' },
                    { name: 'Emergency Exit 2' },
                    { name: 'Emergency Exit 3' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
            {
                name: '5th Floor',
                facilities: [
                    { name: '501 Faculty Research Laboratory 1' },
                    { name: '502 Faculty Research Laboratory 2' },
                    { name: '503 Faculty Research Laboratory 3' },
                    {
                        name: '504 Department of Biology and Environmental Science Conference Room',
                    },
                    {
                        name: '505 Department of Biology and Environmental Science Office',
                    },
                    { name: 'Emergency Exit 1' },
                    { name: 'Emergency Exit 2' },
                    { name: 'Emergency Exit 3' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
            {
                name: '6th Floor',
                facilities: [
                    { name: '601 Bioassay Laboratory' },
                    { name: '602 Histology Laboratory' },
                    { name: '603 Botany Laboratory' },
                    { name: '604 Zoology Laboratory' },
                    { name: '605 Microbiology Laboratory' },
                    { name: '606 Biology Instrumentation Room' },
                    { name: '607 Biology Laboratory Stockroom' },
                    { name: '608 Molecular Biology and Genetics Laboratory' },
                    { name: 'Emergency Exit 1' },
                    { name: 'Emergency Exit 2' },
                    { name: 'Emergency Exit 3' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
        ],
    },

    '5d': {
        id: '5d',
        name: 'Lihangin Hall',
        image: '/assets/images/buildings/lihangin.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Education Research Center' },
                    { name: 'Instructional Materials Center' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Education Technology Labs' },
                    { name: 'Model Classrooms' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },
    '5a': {
        id: '5a',
        name: 'Balay Varangao',
        image: '/assets/images/buildings/varangao.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Education Dean Office' },
                    { name: 'Department of Elementary Education' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Department of Secondary Education' },
                    { name: 'Faculty Rooms' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },
    '5': {
        id: '5',
        name: 'Residence Halls',
        image: '/assets/images/buildings/residence.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Education Administration Office' },
                    { name: 'Lecture Halls' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Faculty Offices' },
                    { name: 'Department of Special Education' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },
    '5b': {
        id: '5b',
        name: 'Lalahon Hall',
        image: '/assets/images/buildings/lalahon.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Department of Physical Education' },
                    { name: 'Sports Science Laboratory' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Department of Health Education' },
                    { name: 'Faculty Rooms' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },
    '5c': {
        id: '5c',
        name: 'Liadlaw Hall',
        image: '/assets/images/buildings/liadlaw.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Guidance and Counseling Center' },
                    { name: 'Student Teaching Office' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Curriculum Development Center' },
                    { name: 'Conference Rooms' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },

    '4': {
        id: '4',
        name: 'Library Building',
        image: '/assets/images/buildings/library.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Learning Commons (Discussion Hall)' },
                    { name: 'Library' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Performing Arts Hall (PAH)' },
                    { name: 'AVR 1' },
                ],
            },
        ],
    },
    '3': {
        id: '3',
        name: 'Technology Innovation Center Building',
        image: '/assets/images/buildings/ticb.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Canteen' },
                    { name: 'Clinic' },
                    { name: 'Male Comfort Room' },
                    { name: 'Female Comfort Room' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    {
                        name: 'Regional Center for Molecular Diagnostic and Research',
                    },
                    {
                        name: 'Safety and Security Unit',
                        email: 'ssu.upcebu@up.edu.ph',
                    },
                    {
                        name: 'Campus Maintenance Office',
                        email: 'ovca.upcebu@up.edu.ph',
                    },
                ],
            },
        ],
    },
    '3b': {
        id: '3b',
        name: 'Clinic',
        image: '/assets/images/buildings/clinic.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Emergency Room' },
                    { name: 'Outpatient Department' },
                    { name: 'Pharmacy' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Medical Records' },
                    { name: 'Laboratory' },
                    { name: 'X-Ray Room' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },
    '3a': {
        id: '3a',
        name: 'Cafeteria',
        image: '/assets/images/buildings/canteen.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: 'Ground Floor',
                facilities: [
                    { name: 'Food Stalls' },
                    { name: 'Dining Area' },
                    { name: 'Kitchen' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },
    '13': {
        id: '13',
        name: 'Cebu Cultural Center',
        image: '/assets/images/random-building.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Law Dean Office' },
                    { name: 'Moot Court' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Law Library' },
                    { name: 'Faculty Rooms' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '3rd Floor',
                facilities: [
                    { name: 'Lecture Rooms' },
                    { name: 'Study Halls' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },
    '11': {
        id: '11',
        name: 'Arts and Sciences (AS) Bldg.',
        image: '/assets/images/buildings/as.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Agriculture Dean Office' },
                    { name: 'Department of Agronomy' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Department of Horticulture' },
                    { name: 'Research Labs' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },
    '11a': {
        id: '11a',
        name: 'AS Conference Hall',
        image: '/assets/images/buildings/asHall.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Soil Testing Laboratory' },
                    { name: 'Plant Tissue Culture Lab' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'Entomology Laboratory' },
                    { name: 'Plant Pathology Lab' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },
    '11b': {
        id: '11b',
        name: 'AS East Wing',
        image: '/assets/images/buildings/asEast.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'AS 160' },
                    { name: 'AS 165' },
                    { name: 'AS 162' },
                    { name: 'AS 161' },
                    { name: 'AS 164' },
                    { name: 'Student Council Room' },
                    {
                        name: 'Ugnayan sg Pahinungod Office (AS 152)',
                        email: 'pahinungod.upc@up.edu.ph',
                    },
                    { name: 'AS 151' },
                    { name: 'AS 150' },
                    { name: 'Male Restroom' },
                    { name: 'Female Restroom' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    {
                        name: 'GAD Office (AS 251)',
                        email: 'gad.upcebu@up.edu.ph',
                    },
                    { name: 'Research Ethics Committee Room (AS 250)' },
                    { name: 'AS 249' },
                    { name: 'AS 248' },
                    { name: 'AS 247' },
                    { name: 'AS 246' },
                    {
                        name: 'Office of Alumni Relations (AS 257)',
                        email: 'oar.upcebu@up.edu.ph',
                    },
                    {
                        name: 'Cebuano Language & Cultural Office (AS 256)',
                        email: 'our.upcebu@up.edu.ph | vaas.upcebu@up.edu.ph',
                    },
                    {
                        name: 'NSTP Office (AS 258)',
                        email: 'nstp.upcebu@up.edu.ph',
                    },
                    { name: 'AS 259' },
                    { name: 'AS 260' },
                    { name: 'AS 261' },
                    { name: 'Male Restroom' },
                    { name: 'Female Restroom' },
                ],
            },
            {
                name: '3rd Floor',
                facilities: [
                    {
                        name: 'Technology Transfer and Business Development Office (TTBDO)',
                        email: 'cebuinit.upcebu@up.edu.ph',
                    },
                    {
                        name: 'LO1 (BloodRed Office)',
                        site: 'www.bloodredclothing.com',
                    },
                    { name: 'LO2 (The Backbone office)' },
                    { name: 'LO3 (Blood Red Office)' },
                    { name: 'LO4 (Artistko)' },
                    { name: 'LO7' },
                    { name: 'LO8' },
                    {
                        name: 'LO6 (R7 Bountiful Maharlika Producers Cooperative)',
                    },
                    { name: 'R07' },
                    { name: 'R06' },
                    { name: 'R05' },
                    { name: 'R03' },
                    { name: 'R02 (Arka Office)', site: 'www.arka.asia' },
                    { name: 'R01' },
                    { name: 'Male Restroom' },
                    { name: 'Female Restroom' },
                ],
            },
        ],
    },
    '11c': {
        id: '11c',
        name: 'AS West Wing',
        image: '/assets/images/buildings/asWest.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'As 144' },
                    { name: 'Faculty Room 1 (AS 146)' },
                    { name: 'Faculty Room 2 (AS 147)' },
                    { name: 'Faculty Room 3 (AS 149)' },
                    {
                        name: 'Office of the Dean, CSS (AS 148)',
                        email: 'css.upcebu@up.edu.ph',
                    },
                    { name: 'Faculty Room 2 (AS 147)' },
                    { name: 'Faculty Room 2 (AS 147)' },
                    { name: 'Faculty Room 2 (AS 147)' },
                    { name: 'AS 138 (Research Office of UP Cebu)' },
                    { name: 'AS 136' },
                    {
                        name: 'Office of the College Secretary - CSS (AS 135)',
                        email: 'ocs_css.upcebu@up.edu.ph',
                    },
                    { name: 'AS 133' },
                    { name: 'AS 134 UP Open University Office - Learning Hub' },
                    { name: 'Male Restroom' },
                    { name: 'Female Restroom' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'AS 239' },
                    { name: 'AS 240' },
                    { name: 'AS 241' },
                    {
                        name: 'Information Technology Center',
                        email: 'itc.upcebu@up.edu.ph',
                    },
                    { name: 'AS 243' },
                    { name: 'AS 244' },
                    { name: 'AS 245' },
                    { name: 'AS 239' },
                    { name: 'AS 235' },
                    { name: 'Math Faculty Lounge' },
                    { name: 'AS 233' },
                    { name: 'AS 231' },
                    { name: 'Male Restroom' },
                    { name: 'Female Restroom' },
                ],
            },
            {
                name: '3rd Floor',
                facilities: [
                    { name: 'AS 310' },
                    { name: 'AS 312 (Statlabs)' },
                    { name: 'AS 313' },
                    {
                        name: 'AS 315 (Robotics and IOT lab)',
                        email: 'itc.upcebu@up.edu.ph',
                    },
                    { name: 'AS 314' },
                    { name: 'AS 316' },
                    { name: 'AS 317' },
                    { name: 'AS 308' },
                    { name: 'AS 306' },
                    {
                        name: 'AS 305 (UP Cebu Department of Computer Science Office)',
                        email: 'dcs.upcebu@up.edu.ph',
                    },
                    { name: 'AS 304' },
                    { name: 'AS 303' },
                    { name: 'AS 302' },
                    { name: 'AS 301' },
                    { name: 'Male Restroom' },
                    { name: 'Female Restroom' },
                ],
            },
        ],
    },
    '14': {
        id: '14',
        name: 'UP High School Cebu',
        image: '/assets/images/buildings/hs.jpg',
        type: 'building',
        slug: null,
        floors: [
            {
                name: '1st Floor',
                facilities: [
                    { name: 'Communication Dean Office' },
                    { name: 'Radio Broadcasting Studio' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '2nd Floor',
                facilities: [
                    { name: 'TV Production Studio' },
                    { name: 'Multimedia Lab' },
                    { name: 'Comfort Rooms' },
                ],
            },
            {
                name: '3rd Floor',
                facilities: [
                    { name: 'Department of Journalism' },
                    { name: 'Department of Communication Studies' },
                    { name: 'Comfort Rooms' },
                ],
            },
        ],
    },

    // Activity locations
    A9: {
        id: 'A9',
        name: 'Amphitheater/Sunset Garden',
        image: '/assets/images/buildings/amphitheater.jpg',
        type: 'activity',
        description:
            'Outdoor performance space for university events and cultural shows.',
        schedule: 'Open for events from 8:00 AM to 10:00 PM',
        capacity: '500 people',
        contactPerson: 'Prof. Maria Santos',
        contactNumber: '123-456-7890',
    },
    A8: {
        id: 'A8',
        name: 'Volleyball Court',
        image: '/assets/images/buildings/volleyball.jpg',
        type: 'activity',
        description:
            'Volleyball and basketball courts for recreational and varsity games.',
        schedule: 'Open daily from 6:00 AM to 9:00 PM',
        capacity: '300 people',
        contactPerson: 'Coach David Rodriguez',
        contactNumber: '123-456-7891',
    },
    A7: {
        id: 'A7',
        name: 'Basketball Court',
        image: '/assets/images/buildings/basketball.jpg',
        type: 'activity',
        description:
            'Full-sized basketball court for recreational play and varsity team practices.',
        schedule: 'Open daily from 6:00 AM to 10:00 PM',
        capacity: '250 people',
        contactPerson: 'Coach Michael Santos',
        contactNumber: '123-456-7890',
    },
    A6: {
        id: 'A6',
        name: 'Undergraduate Cottages',
        image: '/assets/images/buildings/cottageUg.jpg',
        type: 'activity',
        description:
            'Designated area for student camping activities and outdoor events.',
        schedule: 'Available for reservation',
        capacity: '200 people',
        contactPerson: 'Mr. John Rivera',
        contactNumber: '123-456-7892',
    },
    A4: {
        id: 'A4',
        name: 'Admin Field',
        image: '/assets/images/buildings/fieldAdmin.jpg',
        type: 'activity',
        description:
            'Professional archery range for training and competitions.',
        schedule: 'Open Monday to Saturday, 7:00 AM to 5:00 PM',
        capacity: '50 people',
        contactPerson: 'Ms. Diana Fletcher',
        contactNumber: '123-456-7893',
    },
    A2: {
        id: 'A2',
        name: 'Admin Cottages',
        image: '/assets/images/buildings/cottageAdmin.jpg',
        type: 'activity',
        description:
            'Picnic and relaxation area within the university botanical garden.',
        schedule: 'Open daily from 7:00 AM to 6:00 PM',
        capacity: '100 people',
        contactPerson: 'Dr. Elena Mendoza',
        contactNumber: '123-456-7894',
    },
    A3: {
        id: 'A3',
        name: 'Malacañang Cottage',
        image: '/assets/images/buildings/malacs.jpg',
        type: 'activity',
        description:
            'Secondary camping area for student organizational activities.',
        schedule: 'Available by reservation',
        capacity: '150 people',
        contactPerson: 'Ms. Patricia Lim',
        contactNumber: '123-456-7895',
    },
    A1: {
        id: 'A1',
        name: 'Oblation Square',
        image: '/assets/images/buildings/oble.jpg',
        type: 'activity',
        description:
            'Central gathering space for university events and activities.',
        schedule: 'Open 24/7',
        capacity: '1000 people',
        contactPerson: 'University Events Office',
        contactNumber: '123-456-7896',
    },
    A5: {
        id: 'A5',
        name: 'College Mini Stage',
        image: '/assets/images/buildings/stage.jpg',
        type: 'activity',
        description: 'Open space for art installations and exhibitions.',
        schedule: 'Open daily from 8:00 AM to 8:00 PM',
        capacity: '200 people',
        contactPerson: 'Prof. Robert Chen',
        contactNumber: '123-456-7897',
    },
    A10: {
        id: 'A10',
        name: 'High School Open Field',
        image: '/assets/images/buildings/fieldHs.jpg',
        type: 'activity',
        description:
            'Park dedicated to university alumni with monuments and memorials.',
        schedule: 'Open daily from 6:00 AM to 10:00 PM',
        capacity: '300 people',
        contactPerson: 'Alumni Affairs Office',
        contactNumber: '123-456-7898',
    },
    A11: {
        id: 'A11',
        name: 'High School Open Court',
        image: '/assets/images/buildings/courtHsOpen.jpg',
        type: 'activity',
        description:
            'Artificial lagoon for recreation and environmental studies.',
        schedule: 'Open daily from 6:00 AM to 6:00 PM',
        capacity: '150 people',
        contactPerson: 'Environmental Science Department',
        contactNumber: '123-456-7899',
    },
    A12: {
        id: 'A12',
        name: 'High School Covered Court',
        image: '/assets/images/buildings/courtHsCovered.jpg',
        type: 'activity',
        description: 'Quiet space for meditation and mindfulness activities.',
        schedule: 'Open daily from 6:00 AM to 6:00 PM',
        capacity: '50 people',
        contactPerson: 'Student Wellness Center',
        contactNumber: '123-456-7900',
    },
    A13: {
        id: 'A13',
        name: 'Soccer Field',
        image: '/assets/images/buildings/soccer.jpg',
        type: 'activity',
        description:
            'Regulation-size football field for varsity games and practices.',
        schedule: 'Open for scheduled games and practice',
        capacity: '500 people',
        contactPerson: 'Athletics Department',
        contactNumber: '123-456-7901',
    },
    // Security locations
    G1: {
        id: 'G1',
        name: 'Entrance Gate Guard House',
        image: '/assets/images/buildings/guardEntrance.jpg',
        type: 'security',
        personnel: '5 security officers',
        services: [
            'ID verification',
            'Visitor processing',
            'Emergency response',
            'Lost and found',
        ],
        contactNumber: '123-456-8001',
        operatingHours: '24/7',
    },
    G3: {
        id: 'G3',
        name: 'High School Guard House',
        image: '/assets/images/buildings/guardHs.jpg',
        type: 'security',
        personnel: '3 security officers',
        services: [
            'Campus patrol',
            'Student assistance',
            'Emergency response',
            'Property protection',
        ],
        contactNumber: '123-456-8002',
        operatingHours: '24/7',
    },
    G4: {
        id: 'G4',
        name: 'AS Guard House',
        image: '/assets/images/buildings/guardAs.jpg',
        type: 'security',
        personnel: '4 security officers',
        services: [
            'ID verification',
            'Visitor processing',
            'Traffic management',
            'Emergency response',
        ],
        contactNumber: '123-456-8003',
        operatingHours: '24/7',
    },
    G2: {
        id: 'G2',
        name: 'Exit Gate Guard House',
        image: '/assets/images/buildings/guardExit.jpg',
        type: 'security',
        personnel: '3 security officers',
        services: [
            'Campus patrol',
            'Student assistance',
            'Emergency response',
            'Dormitory security',
        ],
        contactNumber: '123-456-8004',
        operatingHours: '24/7',
    },
    // Parking locations
    P1: {
        id: 'P1',
        name: 'COS Bldg. Parking',
        image: '/assets/images/buildings/parkingCos.jpg',
        type: 'security',
        capacity: '30 vehicles',
        description:
            'Designated parking area for College of Science faculty and staff.',
        operatingHours: '6:00 AM to 10:00 PM',
        restrictions: 'Faculty and staff permit required',
        contactNumber: '123-456-8010',
    },
    P2: {
        id: 'P2',
        name: 'Canteen Parking',
        image: '/assets/images/buildings/parkingCanteen.jpg',
        type: 'security',
        capacity: '25 vehicles',
        description: 'Short-term parking for canteen and cafeteria visitors.',
        operatingHours: '6:00 AM to 9:00 PM',
        restrictions: 'Maximum 2-hour parking',
        contactNumber: '123-456-8011',
    },
    P3: {
        id: 'P3',
        name: 'Library Parking',
        image: '/assets/images/buildings/parkingLibrary.jpg',
        type: 'security',
        capacity: '40 vehicles',
        description:
            'Parking area serving the library and surrounding academic buildings.',
        operatingHours: '6:00 AM to 10:00 PM',
        restrictions: 'University ID required',
        contactNumber: '123-456-8012',
    },
    P4: {
        id: 'P4',
        name: 'Motorcycle Parking',
        image: '/assets/images/buildings/parkingMotor.jpg',
        type: 'security',
        capacity: '60 motorcycles',
        description: 'Main motorcycle parking area for students and visitors.',
        operatingHours: '24/7',
        restrictions: 'Motorcycles only',
        contactNumber: '123-456-8013',
    },
    P5: {
        id: 'P5',
        name: 'Undergraduate Bldg. Parking',
        image: '/assets/images/buildings/parkingUndergrad.jpg',
        type: 'security',
        capacity: '35 vehicles',
        description: 'Parking lot adjacent to the Undergraduate Building.',
        operatingHours: '6:00 AM to 9:00 PM',
        restrictions: 'Student and faculty permit required',
        contactNumber: '123-456-8014',
    },
    P6: {
        id: 'P6',
        name: 'AS Motorcycle Parking',
        image: '/assets/images/buildings/parkingMotorAs.jpg',
        type: 'security',
        capacity: '50 motorcycles',
        description:
            'Motorcycle parking for Arts and Sciences students and faculty.',
        operatingHours: '24/7',
        restrictions: 'Motorcycles only, AS department permit required',
        contactNumber: '123-456-8015',
    },
    P7: {
        id: 'P7',
        name: 'AS Parking',
        image: '/assets/images/buildings/parkingAs.jpg',
        type: 'security',
        capacity: '45 vehicles',
        description:
            'Car parking area serving the Arts and Sciences buildings.',
        operatingHours: '6:00 AM to 10:00 PM',
        restrictions: 'AS faculty and staff priority',
        contactNumber: '123-456-8016',
    },
};
